mineral_catalogue/catalogue/urls.py
from django.urls import path
from . import views

app_name = "catalogue"

urlpatterns = [
    path('mineral/<int:pk>', views.mineral_detail, name='detail'),
    path('', views.home, name='home'),
    path('random', views.random_detail, name='random'),
]

mineral_catalogue/mineral_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogue.urls', namespace="catalogue")),
]

mineral_catalogue/catalogue/models.py
from django.db import models


class Mineral(models.Model):
    name = models.CharField(unique=True, max_length=255)
    image_filename = models.CharField(max_length=255)
    image_caption = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    group = models.CharField(max_length=255)
    strunz_classification = models.CharField(blank=True, max_length=255)
    color = models.CharField(blank=True, max_length=255)
    crystal_system = models.CharField(blank=True, max_length=255)
    unit_cell = models.CharField(blank=True, max_length=255)
    crystal_symmetry = models.CharField(blank=True, max_length=255)
    cleavage = models.CharField(blank=True, max_length=255)
    mohs_scale_hardness = models.CharField(blank=True, max_length=255)
    luster = models.CharField(blank=True, max_length=255)
    streak = models.CharField(blank=True, max_length=255)
    diaphaneity = models.CharField(blank=True, max_length=255)
    optical_properties = models.CharField(blank=True, max_length=255)
    refractive_index = models.CharField(blank=True, max_length=255)
    crystal_habit = models.CharField(blank=True, max_length=255)
    specific_gravity = models.CharField(blank=True, max_length=255)

    def __str__(self):
        return self.name

mineral_catalogue/catalogue/views.py
from django.shortcuts import render
import json
from .models import Mineral
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
import random


def make_minerals(mineral):
    fields = {
        'name': None,
        'image filename': None,
        'image caption': None,
        'category': None,
        'formula': None,
        'group': None,
        'strunz classification': None,
        'crystal system': None,
        'unit cell': None,
        'color': None,
        'crystal symmetry': None,
        'cleavage': None,
        'mohs scale hardness': None,
        'luster': None,
        'streak': None,
        'diaphaneity': None,
        'optical properties': None,
        'refractive index': None,
        'crystal habit': None,
        'specific gravity': None,
    }
    for key, value in mineral.items():
        fields[key] = value
    return fields


def add_to_database():
    with open('minerals.json', encoding='utf-8') as file:
        minerals = json.load(file)
        for mineral in minerals:
            try:
                fields = make_minerals(mineral)
                Mineral(
                    name=fields['name'],
                    image_filename=fields['image filename'],
                    image_caption=fields['image caption'],
                    category=fields['category'],
                    formula=fields['formula'],
                    group=fields['group'],
                    strunz_classification=fields['strunz classification'],
                    crystal_system=fields['crystal system'],
                    unit_cell=fields['unit cell'],
                    color=fields['color'],
                    crystal_symmetry=fields['crystal symmetry'],
                    cleavage=fields['cleavage'],
                    mohs_scale_hardness=fields['mohs scale hardness'],
                    luster=fields['luster'],
                    streak=fields['streak'],
                    diaphaneity=fields['diaphaneity'],
                    optical_properties=fields['optical properties'],
                    refractive_index=fields['refractive index'],
                    crystal_habit=fields['crystal habit'],
                    specific_gravity=fields['specific gravity']
                ).save()
            except IntegrityError:
                continue


def home(request):
    add_to_database()
    minerals = Mineral.objects.all()
    return render(request, 'catalogue/home.html', {'minerals': minerals})


def mineral_detail(request, pk):
    mineral = get_object_or_404(Mineral, pk=pk)
    return render(request, 'catalogue/detail.html', {'mineral': mineral})


def random_detail(request):
    all_minerals = Mineral.objects.all()
    mineral = random.choice(all_minerals)
    return render(request, 'catalogue/detail.html', {'mineral': mineral})

mineral_catalogue/catalogue/templates/catalogue/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'catalogue/main.css' %}">
        <title>Mineral Catalogue</title>
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'catalogue:home' %}">Mineral Catalogue</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'catalogue:random' %}">Random Mineral</a>
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            {% block content %}{% endblock %}
        </div>
    </div>
</main>

</body>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

mineral_catalogue/catalogue/templates/catalogue/detail.html
{% extends "catalogue/base.html" %}
{% load static %}

{% block content %}
<article class="media content-section">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-4">
                <h1 class="mineral__name">{{ mineral.name|title }}</h1>
                <img src="{% static 'catalogue/images/' %}{{ mineral.name }}.jpg"/>
                <p class="mineral__caption">{{ mineral.image_caption }}</p>
            </div>
            <div class="col-md-8 col-sm-8 col-xs8">
            <br>
                <table class="table">
                    <tr>
                        <td class="mineral__category">Category</td>
                        <td>{{ mineral.category }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Formula</td>
                        <td class="mineral__formula">{{ mineral.formula|safe }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Group</td>
                        <td>{{ mineral.group }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Strunz Classification</td>
                        <td>{{ mineral.strunz_classification }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal System</td>
                        <td>{{ mineral.crystal_system }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Unit Cell</td>
                        <td>{{ mineral.unit_cell }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Color</td>
                        <td>{{ mineral.color }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal Symmetry</td>
                        <td>{{ mineral.crystal_symmetry }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Cleavage</td>
                        <td>{{ mineral.cleavage }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Mohs Scale Hardness</td>
                        <td>{{ mineral.mohs_scale_hardness }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Luster</td>
                        <td>{{ mineral.luster }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Streak</td>
                        <td>{{ mineral.streak }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Diaphaneity</td>
                        <td>{{ mineral.diaphaneity }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Optical Properties</td>
                        <td>{{ mineral.optical_properties }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Refractive Index</td>
                        <td>{{ mineral.refractive_index }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal Habit</td>
                        <td>{{ mineral.crystal_habit }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Specific Gravity</td>
                        <td>{{ mineral.specific_gravity }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</article>
{% endblock content %}

mineral_catalogue/catalogue/templates/catalogue/home.html
{% extends "catalogue/base.html" %}

{% block content %}
    <div class="mineral__container">
        <div class="row">
        {% for mineral in minerals %}
            {% if forloop.counter0|divisibleby:3 %}
                </div><br><div class="row">
            {% endif %}
            <div class="col-4">
                <a class="minerals__anchor" href="{% url 'catalogue:detail' pk=mineral.pk %}">{{ mineral.name|title }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}